### PR TITLE
add post - The role of smart contracts in secure software development

### PR DESCRIPTION
**Pull request by m0rphtail**

### CODE REVIEW

**Comment by maektwain** [comment]
Did you test it ?

**Comment by m0rphtail** [comment]
no, how do i test it locally?

**Comment by maektwain** [comment]
> no, how do i test it locally?

You can see the PR deploy Netlify. Maybe check the deploy side on the PR

**Comment by m0rphtail** [comment]
The deploy log says
```
There was an error in the GraphQL query
Field "image" must not have a selection since type "String" has no subfields.
```

**Comment by m0rphtail** [comment]
looks like its done @maektwain

**Pull request merged**
