### PR TITLE
Implementing a loan scheduler change in Fineract 1.x.

### PR DESCRIPTION
**Pull request by xurror**
Publication for Implementing a loan scheduler change in Fineract 1.x.

### CODE REVIEW

**Comment by xurror** [comment]
@Ankit-muellner @maektwain please review.

**Comment by Ankit-muellner** [comment]
PR Looks good @xurror but again has failed checks though. can you investigate first.

**Comment by xurror** [comment]
It says it's due to some graphql configuration for AuthorYaml. I have not acted on that part of the code so I want to believe I'm not at the origin of this error.

**Comment by Devilla** [comment]
@xurror  see the error is in ```deploy logs```. :rocket: 
```
YAMLException: bad indentation of a sequence entry at line 43, column 3:
3:44:52 PM:         - id: Kaze Nasser
```
Correct the indentation of ```- id: Kaze Nasser``` to the left. :1st_place_medal:

**Comment by Devilla** [comment]
@xurror yeah the checks are fine :rocket: but there's a lot of improvements can be done like spacing, especially text adjacent to hyperlinks please correct that so it looks good. :+1:

**Comment by Ankit-muellner** [comment]
@xurror @Devilla Kaze, can you please quickly resolve any improvements on ur end so that we move towards closing this PR.

**Comment by Devilla** [comment]
> @xurror @Devilla Kaze, can you please quickly resolve any improvements on ur end so that we move towards closing this PR.

Yeah, @xurror just fix the spacing issues later we can resolve more with grammerly tool.

**Review by Devilla — APPROVED** [review]

**Comment by Devilla** [comment]
@Ankit-muellner @xurror I've reviewed and fixed some typos please let me know if images are visible to you, if so then merge it too. :rocket:

**Pull request merged**
