### PR TITLE
Re-engineering holiday based rescheduling capabilities in Fineract 1……

### PR DESCRIPTION
**Pull request by xurror**
Pulblication for holiday rescheduler

### CODE REVIEW

**Comment by xurror** [comment]
@Ankit-muellner Here.

**Comment by Devilla** [comment]
@xurror Please check 'Deploy logs".
```
YAMLException: bad indentation of a sequence entry at line 43, column 3:
3:44:52 PM:         - id: Kaze Nasser
```

**Comment by xurror** [comment]
@Ankit-muellner All Checks here.

**Comment by maektwain** [comment]
The content formatting looks quite non-impressive. It seems lot of H1 are used why not just use the h3 or small title like markdown. Maybe try and change them, before for final push

**Comment by xurror** [comment]
So, I've removed the H1s

**Comment by Devilla** [comment]
> So, I've removed the H1s

Yeah, looks better now but there's a lot of little typos maybe you can use a tool like Grammarly for that. :blue_book:

**Comment by xurror** [comment]
Ok. Let me get to it.

**Comment by Ankit-muellner** [comment]
@xurror @Devilla What's the stat here? Do you guys wanna review and close this now?

**Comment by maektwain** [comment]
BTW @xurror we can get access for Grammarlly for you , if you wish to have one. Thanks

**Comment by Devilla** [comment]
> BTW @xurror we can get access for Grammarlly for you , if you wish to have one. Thanks

Yeah, Grammarlly would be great for these little issues, otherwise @xurror we have to go through these human errors everytime which would not be a good practice. 👍

**Pull request merged**
